import { Conversation, Message, ChannelConfig } from './types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    leadId: 'l1',
    leadName: 'Ahmed Al Maktoum',
    leadPhone: '+971 50 123 4567',
    leadEmail: 'ahmed@example.com',
    leadStage: 'Hot Lead',
    channel: 'whatsapp',
    lastMessage: 'I am interested in the Palm Jumeirah villa. Can we schedule a viewing?',
    lastMessageTime: new Date(Date.now() - 5 * 60000),
    unreadCount: 2,
    status: 'open',
    isPinned: true,
    assignedAgent: 'Sarah Ahmed',
  },
  {
    id: '2',
    leadId: 'l2',
    leadName: 'Fatima Hassan',
    leadPhone: '+971 55 987 6543',
    leadStage: 'New Lead',
    channel: 'messenger',
    lastMessage: 'What is the price range for apartments in Downtown Dubai?',
    lastMessageTime: new Date(Date.now() - 30 * 60000),
    unreadCount: 1,
    status: 'open',
    assignedAgent: 'Mohammed Ali',
  },
  {
    id: '3',
    leadId: 'l3',
    leadName: 'John Smith',
    leadEmail: 'john.smith@gmail.com',
    leadStage: 'Meeting Scheduled',
    channel: 'email',
    lastMessage: 'Thank you for the brochure. I will review and get back to you.',
    lastMessageTime: new Date(Date.now() - 2 * 3600000),
    unreadCount: 0,
    status: 'open',
    assignedAgent: 'Sarah Ahmed',
  },
  {
    id: '4',
    leadId: 'l4',
    leadName: 'Maria Garcia',
    leadPhone: '+1 555 123 4567',
    leadStage: 'Follow Up',
    channel: 'sms',
    lastMessage: 'Please call me tomorrow at 10am',
    lastMessageTime: new Date(Date.now() - 5 * 3600000),
    unreadCount: 0,
    status: 'pending',
    assignedAgent: 'Ahmed Kaabi',
  },
  {
    id: '5',
    leadId: 'l5',
    leadName: 'خالد العتيبي',
    leadPhone: '+966 50 111 2222',
    leadStage: 'Qualified',
    channel: 'whatsapp',
    lastMessage: 'أريد معرفة المزيد عن المشروع الجديد',
    lastMessageTime: new Date(Date.now() - 24 * 3600000),
    unreadCount: 3,
    status: 'open',
    isPinned: true,
    assignedAgent: 'Sarah Ahmed',
  },
  {
    id: '6',
    leadId: 'l6',
    leadName: 'Emma Wilson',
    leadEmail: 'emma.w@company.com',
    leadStage: 'Cold Lead',
    channel: 'email',
    lastMessage: 'Not interested at the moment, please follow up next quarter.',
    lastMessageTime: new Date(Date.now() - 48 * 3600000),
    unreadCount: 0,
    status: 'archived',
  },
];

export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversationId: '1',
      content: 'Hello! I saw your listing on Property Finder for the Palm Jumeirah villa.',
      sender: 'lead',
      channel: 'whatsapp',
      timestamp: new Date(Date.now() - 60 * 60000),
      status: 'read',
    },
    {
      id: 'm2',
      conversationId: '1',
      content: 'Hi Ahmed! Thank you for your interest. Yes, that beautiful 5-bedroom villa is still available. Would you like to know more details?',
      sender: 'agent',
      channel: 'whatsapp',
      timestamp: new Date(Date.now() - 55 * 60000),
      status: 'read',
    },
    {
      id: 'm3',
      conversationId: '1',
      content: 'Yes please! What is the asking price and the plot size?',
      sender: 'lead',
      channel: 'whatsapp',
      timestamp: new Date(Date.now() - 50 * 60000),
      status: 'read',
    },
    {
      id: 'm4',
      conversationId: '1',
      content: 'The asking price is AED 25,000,000. The plot size is 8,500 sqft with a built-up area of 6,200 sqft. It includes a private beach, pool, and smart home features.',
      sender: 'agent',
      channel: 'whatsapp',
      timestamp: new Date(Date.now() - 45 * 60000),
      status: 'read',
    },
    {
      id: 'm5',
      conversationId: '1',
      content: 'I am interested in the Palm Jumeirah villa. Can we schedule a viewing?',
      sender: 'lead',
      channel: 'whatsapp',
      timestamp: new Date(Date.now() - 5 * 60000),
      status: 'delivered',
    },
  ],
  '2': [
    {
      id: 'm1',
      conversationId: '2',
      content: 'Hi, I am looking for a 2-bedroom apartment in Downtown Dubai.',
      sender: 'lead',
      channel: 'messenger',
      timestamp: new Date(Date.now() - 120 * 60000),
      status: 'read',
    },
    {
      id: 'm2',
      conversationId: '2',
      content: 'Hello Fatima! Great choice. We have several options available. What is your budget range?',
      sender: 'agent',
      channel: 'messenger',
      timestamp: new Date(Date.now() - 100 * 60000),
      status: 'read',
    },
    {
      id: 'm3',
      conversationId: '2',
      content: 'What is the price range for apartments in Downtown Dubai?',
      sender: 'lead',
      channel: 'messenger',
      timestamp: new Date(Date.now() - 30 * 60000),
      status: 'delivered',
    },
  ],
};

export const mockChannelConfigs: ChannelConfig[] = [
  {
    id: 'ch1',
    channel: 'whatsapp',
    name: 'WhatsApp Business',
    status: 'connected',
    accountName: '+971 4 123 4567',
    lastSync: new Date(Date.now() - 5 * 60000),
  },
  {
    id: 'ch2',
    channel: 'messenger',
    name: 'Meta Messenger',
    status: 'connected',
    accountName: 'OneLinker Real Estate',
    lastSync: new Date(Date.now() - 10 * 60000),
  },
  {
    id: 'ch3',
    channel: 'email',
    name: 'Email (Resend)',
    status: 'connected',
    accountName: 'support@onelinker.com',
    lastSync: new Date(Date.now() - 2 * 60000),
  },
  {
    id: 'ch4',
    channel: 'sms',
    name: 'SMS (Twilio)',
    status: 'disconnected',
  },
  {
    id: 'ch5',
    channel: 'telegram',
    name: 'Telegram Bot',
    status: 'error',
    accountName: '@OneLinkerBot',
  },
  {
    id: 'ch6',
    channel: 'instagram',
    name: 'Instagram DM',
    status: 'connected',
    accountName: '@onelinker_realestate',
    lastSync: new Date(Date.now() - 15 * 60000),
  },
];

export const quickReplies = [
  { id: '1', title: 'Greeting', content: 'Hello! Thank you for reaching out to OneLinker Real Estate. How can I assist you today?' },
  { id: '2', title: 'Schedule Viewing', content: 'I would be happy to schedule a property viewing for you. What dates and times work best for your schedule?' },
  { id: '3', title: 'Request Budget', content: 'To better assist you, could you please share your budget range and preferred locations?' },
  { id: '4', title: 'Send Brochure', content: 'I am attaching the property brochure for your review. Please let me know if you have any questions.' },
  { id: '5', title: 'Follow Up', content: 'Hi! I wanted to follow up on our previous conversation. Have you had a chance to review the properties I shared?' },
  { id: '6', title: 'Closing', content: 'Thank you for your interest. Please do not hesitate to reach out if you have any further questions. Have a great day!' },
];
